---
Core-Switch-01:
  hostname: "10.1.1.1"
  groups:
    - cisco_ios
  data:
    native_vlan: 99
    role: "backbone_core"

Dist-Switch-A:
  hostname: "10.1.1.2"
  groups:
    - cisco_ios
  data:
    native_vlan: 99
    role: "distribution"
